# -*- coding: utf-8 -*-
"""calculative_foundation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FuB85Atu_9bVRKdCxg50YPILVKKhYaLW

# **Calculative Foundation Project**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy.linalg import norm, inv, det, eig
from scipy.linalg import lu, svd
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

"""# **Create Dataset (Students × Subjects)**"""

data = {
    "Math": [78, 85, 90, 66, 72],
    "Physics": [82, 88, 94, 70, 75],
    "Chemistry": [80, 86, 91, 65, 74],
    "English": [75, 79, 84, 68, 73]
}

df = pd.DataFrame(data)
df

plt.hist(df['Math'], bins=10)
plt.title("Distribution of Math Scores")
plt.xlabel("Score")
plt.ylabel("Number of Students")
plt.show()

df.mean().plot(kind='bar')
plt.title("Average Score per Subject")
plt.show()

plt.imshow(df.corr())
plt.colorbar()
plt.title("Correlation Matrix")
plt.show()

"""**Matrix form:**"""

A = df.values
A

"""# **VECTOR & MATRIX FUNDAMENTALS**

**Represent each student as a vector**
"""

v1 = df.iloc[0].values
v2 = df.iloc[1].values

print("Student 1 Vector:", v1)
print("Student 2 Vector:", v2)

v1 = np.array([70,80])
v2 = np.array([60,90])

plt.quiver(0,0,v1[0],v1[1],angles='xy',scale_units='xy',scale=1)
plt.quiver(0,0,v2[0],v2[1],angles='xy',scale_units='xy',scale=1)
plt.xlim(0,100)
plt.ylim(0,100)
plt.show()

"""**Compute Norm-1 and Norm-2**"""

norm1 = norm(v1, 1)
norm2 = norm(v1)

print("L1 Norm:", norm1)
print("L2 Norm:", norm2)

"""**Dot Product & Angle Between Vectors**"""

dot_product = np.dot(v1, v2)

angle = np.arccos(dot_product / (norm(v1)*norm(v2)))
angle_deg = np.degrees(angle)

print("Dot Product:", dot_product)
print("Angle (degrees):", angle_deg)

"""**Cross Product**"""

cross_product = np.cross(v1[:3], v2[:3])
print("Cross Product:", cross_product)

"""**Projection of One Vector onto Another**"""

projection = (np.dot(v1, v2) / np.dot(v2, v2)) * v2
print("Projection of v1 onto v2:", projection)

"""# **MATRIX OPERATIONS**

**Matrix Addition**
"""

B = A + A

print("Addition:\n", B)

"""**Matrix Multiplication**"""

C = np.dot(A.T, A)

print("Multiplication:\n", C)

"""**Transpose**"""

A_transpose
print("Transpose:\n", A)

"""**Determinant**"""

square_matrix = A[:4,:4]

print("Determinant:", det(square_matrix))

"""**Inverse**"""

print("Inverse:\n", inv(square_matrix))

"""# **EIGENVALUES & DECOMPOSITION**

**Covariance Matrix**
"""

cov_matrix = np.cov(A.T)
cov_matrix

"""**Eigenvalues & Eigenvectors**"""

eigenvalues, eigenvectors = eig(cov_matrix)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

"""**LU Decomposition**"""

P, L, U = lu(square_matrix)

print("L Matrix:\n", L)
print("U Matrix:\n", U)

"""**Singular Value Decomposition (SVD)**"""

U, S, VT = svd(A)

print("Singular Values:", S)

"""# **DIMENSIONALITY REDUCTION**

**PCA (Reduce to 2D)**
"""

pca = PCA(n_components=2)
pca_result = pca.fit_transform(A)

print(pca_result)

pca = PCA(n_components=2)
reduced = pca.fit_transform(df)

plt.scatter(reduced[:,0], reduced[:,1])
plt.title("PCA 2D Projection")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

"""**LDA Classification**"""

labels = ["Above","Above","Above","Below","Below"]

lda = LinearDiscriminantAnalysis(n_components=1)
lda_result = lda.fit_transform(A, labels)

print(lda_result)